# This file configures the viender application frontend. The frontend serves
# public web traffic.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: viender-frontend
  labels:
    app: viender
# The viender frontend replica set ensures that at least 3
# instances of the viender app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: viender
        tier: frontend
    spec:
      containers:
      - name: viender-app
        # Replace $GCLOUD_PROJECT with your project ID or use `make template`.
        image: repo.treescale.com/viender/viender
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        # The viender process listens on port 8080 for web traffic by default.
        ports:
        - name: http-server
          containerPort: 8080
      imagePullSecrets:
      - name: regsecret

